### ISSUE TITLE
What is the NBA-SHOTS-DB_DATABASE_PASSWORD

### ISSUE THREAD

**Issue by luzer** [toddwschneider/nba-shots-db#2]
i cannot find it,
i am trying to connect to the local postgres DB

**Comment by toddwschneider** [comment]
@luzer that's a config variable used to connect to your production Postgres database. You should not need to set it to connect to your local development Postgres database.

I'd recommend checking out the Rails guide for configuring Postgres: http://guides.rubyonrails.org/configuring.html#configuring-a-postgresql-database

**Comment by luzer** [comment]
thanks! it worked
